#!/usr/bin/env bash

root="$(dirname "$0")/.."
target_tmux="$HOME/.tmux.conf"
target_nvim="$HOME/.config/nvim"

function panic() {
  echo "$@"
  exit 1
}

case "$1" in
    -h|--help)
        echo "Usage: $(basename "$0") [-f|--force]"
        exit 0
        ;;
    -f|--force)
        ;;
    *)
        [[ -f "$target_tmux" ]] && panic "$target_tmux exists. Use -f to overwrite."
        [[ -d "$target_nvim" ]] && panic "$target_nvim exists. Use -f to overwrite."
        ;;
esac

if [[ ! -f "$root/.env" ]]; then
  panic 'There is no .env file.'
fi

function overwrite_tmux() {
  set -a
  source "$root/.env"
  set +a
  envsubst < "$root/.tmux.conf.template"
}

overwrite_tmux > "$target_tmux"
rm -rf "$target_nvim" && cp -R "$root/nvim" "$target_nvim"
